"""The list of securities the project covers.

Kept as a file in the repository rather than worked out at run time, so a
result from six months ago says exactly which securities it was measured over.
A universe that quietly grows between runs makes two accuracy numbers
incomparable without anyone noticing.

The US file is generated by `scripts/build_us_universe.py`, which reads names
and central index keys from the SEC rather than trusting anything typed by
hand.
"""

from __future__ import annotations

import json
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Literal

from stockagent.data.models import Alias, Currency, Market, Security

US_UNIVERSE = Path("data/universe/us.json")
NGX_UNIVERSE = Path("data/universe/ngx.json")


@dataclass(frozen=True)
class UniverseEntry:
    """A security, plus the identifiers needed to go and fetch data for it."""

    ticker: str
    market: Market
    name: str
    currency: Currency
    role: Literal["company", "benchmark"] = "company"
    # SEC central index key. US only; the key into EDGAR for company facts.
    cik: int | None = None
    exchange: str | None = None
    aliases: tuple[Alias, ...] = ()

    @property
    def is_benchmark(self) -> bool:
        return self.role == "benchmark"

    def to_security(self) -> Security:
        return Security(
            ticker=self.ticker,
            market=self.market,
            name=self.name,
            currency=self.currency,
            aliases=self.aliases,
        )


def _entry_from_json(row: dict) -> UniverseEntry:
    return UniverseEntry(
        ticker=row["ticker"],
        market=row["market"],
        name=row["name"],
        currency=row["currency"],
        role=row.get("role", "company"),
        cik=row.get("cik"),
        exchange=row.get("exchange"),
        aliases=tuple(
            Alias(
                text=alias["text"],
                kind=alias["kind"],
                until=_optional_date(alias.get("until")),
            )
            for alias in row.get("aliases", [])
        ),
    )


def _optional_date(value: str | None) -> date | None:
    return date.fromisoformat(value) if value else None


def load_universe(path: str | Path) -> list[UniverseEntry]:
    rows = json.loads(Path(path).read_text())
    return [_entry_from_json(row) for row in rows]


def companies(entries: Iterable[UniverseEntry]) -> list[UniverseEntry]:
    return [entry for entry in entries if not entry.is_benchmark]


def benchmark(entries: Iterable[UniverseEntry]) -> UniverseEntry | None:
    """The market benchmark, if the universe names one.

    Returns None rather than raising: a market can be collected before its
    benchmark is available, and "did it beat the market" simply cannot be
    asked until one exists.
    """
    for entry in entries:
        if entry.is_benchmark:
            return entry
    return None
